# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

det_etat <- function(nb, ep, fp, gp, seuil, max_gpe) {
    .Call('_gridy_det_etat', PACKAGE = 'gridy', nb, ep, fp, gp, seuil, max_gpe)
}

det_etat_tot <- function(id_car_pere, etats_pere, forces_pere, groupes_pere, id_car_pere_fils, nb_obs_fils, seuil) {
    .Call('_gridy_det_etat_tot', PACKAGE = 'gridy', id_car_pere, etats_pere, forces_pere, groupes_pere, id_car_pere_fils, nb_obs_fils, seuil)
}

